AWSTemplateFormatVersion: "2010-09-09"
Description: Simple Application Architecture(VPC,Subnet,IGW,NAT,EIP,RTB,EC2)

Parameters:
  EC2InstanceType:
    Description: EC2 instance type on which IDE runs
    Type:        String
    Default:     t2.small
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium

  StreamingLabName:
    Description: VPC Prefix
    Type: String
    Default: AccountID(email)
  

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "Streaming-CF-${StreamingLabName}-VPC"

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.0.0/16
      AvailabilityZone: "ap-northeast-2a"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "Streaming-CF-${StreamingLabName}-PublicSubnet1"
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "Streaming-CF-${StreamingLabName}-IGW"

  AttachIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref IGW
      VpcId:  !Ref MyVPC

  PublicRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: !Sub "Streaming-CF-${StreamingLabName}-Public RouteTable"

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachIGW
    Properties:
      RouteTableId: !Ref PublicRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  PublicSubnetRTAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRT
      SubnetId: !Ref PublicSubnet1

  C9IDE:
    Type: 'AWS::Cloud9::EnvironmentEC2'
    Properties:
      Name: !Sub '${StreamingLabName}-Cloud9-IDE'
      Description: !Sub '${StreamingLabName} Cloud9 IDE'
      AutomaticStopTimeMinutes: 60
      SubnetId: !Ref PublicSubnet1
      InstanceType: !Ref 'EC2InstanceType'

Outputs:

  Cloud9URL:
    Description: Cloud9 Environment
    Value:
      Fn::Join:
      - ''
      - - !Sub https://${AWS::Region}.console.aws.amazon.com/cloud9/ide/
        - !Ref 'C9IDE'